apiVersion: v1
kind: PersistentVolume
metadata:
  name: homelab-pv
spec:
  capacity:
    storage: 750Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /mnt/data/homelab-pv
    server: 172.16.1.20
  mountOptions:
  - nolock
  - vers=4.1