apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.16.100.0-172.16.110.0
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: homelabl2advertisement
  namespace: metallb-system